### ISSUE TITLE
Connecting with Trakt from the button does nothing after authorizing TraktRoller

### ISSUE THREAD

**Issue by justalemon** [sttz/TraktRoller#9]
Lately I have been unable to use TraktRoller because clicking the "Connect with Trakt" button and authorizing the Trakt App does nothing. After completing the authorization flow, I still get the footer button with "Connect with Trakt" even if the cookies exist and has access to my Trakt account.

I tried clearing the cookies of both Crunchyroll and Trakt and repeating the process but it still doesn't work.

* TraktRoller 31ac0e7fb2a2286af946875e2ba3a11da43709cc
* Tampermonkey 4.9
* Vivaldi 2.9.1705.41

**Comment by sttz** [comment]
Hey, I tried with Vivaldi and Tampermonkey and could connect properly.

After you authorize the app on Trakt and get redirect back to Crunchyroll, does the `code` and `state` url parameters get removed? Do you get any Trakt-related errors in the console?

**Comment by justalemon** [comment]
> Do you get any Trakt-related errors in the console?

I found a "Blocked by Client" error so I started looking at my other extensions to find out what was blocking the Trakt API. As it turns out, Privacy Badger was blocking api.trakt.tv and that was preventing the script from working.

I have reported it on EFForg/privacybadger#2524 so this can now be closed.
